version: "3.8"
services: 
  database:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: svalyn
      POSTGRES_USER: test_username
      POSTGRES_PASSWORD: test_password
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/svalyn
      SPRING_DATASOURCE_USERNAME: test_username
      SPRING_DATASOURCE_PASSWORD: test_password
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - database