name: Docker Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-push heroku
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HEROKU_USERNAME }}
          password: ${{ secrets.HEROKU_PASSWORD }}
          registry: registry.heroku.com
          repository: svalyn/web
          tags: latest